### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by ivankristianto** [comfusion/hyperdrive#4]
Adding a unit testing would be a great addition

**Comment by jhabdas** [comment]
> Adding a unit testing would be a great addition

Agreed and it's necessary to enable refactoring without _as much_ fear of introducing breaking changes as the plugin rolls forward. Not sure of the best toolset for the job. But maybe the peeps at https://github.com/KnowTheCode/ have a suggestion.

**Comment by jhabdas** [comment]
https://github.com/gedex/wc-ubud-2017

**Comment by eriktorsner** [comment]
Hi,

Your code is fun to read! :-) But I'm going to be a bit boring and say that it might not be very well suited for effective unit tests using something like WP_Mock.

I'd be willing to help out with setting up the needed unit tests and hook up with Travi-CI etc, but I'd really like to do some refactoring as part of the process. Less global functions and more OOP. Interested?

**Comment by jhabdas** [comment]
> Your code is fun to read!

Thank you kindly.

> I'd be willing to help out with setting up the needed unit tests and hook up with Travi-CI etc, but I'd really like to do some refactoring as part of the process.

Until 1.0.0 pulls with refactoring are likely to be rejected. But I have no qualms reading reviewing them to gain insights. Regarding OO, I'm highly adverse and would prefer to see use of functional programming with use of namespacing.

Thanks for mentioning `WP_Mock`. I haven't looked at it yet but if you'd like to fork and prepare a minimal example of one unit testing being run using it I'd be much obliged.

**Comment by jhabdas** [comment]
https://github.com/codeclimate/php-test-reporter

**Comment by jhabdas** [comment]
Blocked by #9

**Comment by jhabdas** [comment]
Blocked by https://github.com/comfusion/hyperdrive/issues/32

**Comment by jhabdas** [comment]
With #9 and #32 completed today this is no longer blocked. We now have Continuous Integration, a test scaffold and code coverage reporting to work against. As soon as it hits a reasonable feature development may resume.

[![Test Coverage](https://codeclimate.com/github/Microsoft/TypeScript/badges/coverage.svg)](https://codeclimate.com/github/Microsoft/TypeScript)

**Comment by jhabdas** [comment]
Still researching best practices on creating unit tests and, as a result, have posted the following question in hopes of gathering more information: https://codesymphony.co/writing-wordpress-plugin-unit-tests/comment-page-1/#comment-8236

**Comment by jhabdas** [comment]
We will write tests in classes just as soon as that becomes a necessity. Meanwhile we will write our tests using: https://github.com/kahlan/kahlan

**Comment by jhabdas** [comment]
Blocked by https://github.com/comfusion/hyperdrive/issues/40

**Comment by jhabdas** [comment]
For the curious space traveler wondering why I'm vehemently opposed to OOP in this codebase, here's a place to start: https://wordpress.stackexchange.com/questions/5777/using-oop-in-themes

**Comment by jhabdas** [comment]
https://github.com/antecedent/patchwork
https://brain-wp.github.io/BrainMonkey/

**Comment by jhabdas** [comment]
Blocked by https://github.com/comfusion/hyperdrive/issues/56

**Comment by jhabdas** [comment]
Calling this done as we now have the the ability to create and cover both unit and integration tests, as well as perform automated code style analysis using WP Core guidelines for plugins, with the option to upgrade to VIP plug-in checking with the change of a single line of code.

Here is our build matrix, which tests unit and integration coverage:

<img width="986" alt="screen shot 2017-05-24 at 5 08 57 pm" src="https://cloud.githubusercontent.com/assets/440298/26395799/cc5c2aa8-40a3-11e7-9494-c7dcb07f0711.png">

This test matrix includes the following tests:

- Unit testing with coverage reporting for all supported versions of PHP
- Integration testing against both WP single and multi-site integrations
- Code coverage analysis separated by tag `unittests` and `integration`
- Automated code style checking for WP conformance

**Note:** WP style guidelines _only_ apply to plug-in code (stored in `src/`). Every other PHP file in the application will use 2 spaces for indentation to reduce rightward code drift.

Our unit testing enables us to write our unit tests using `describe-it` syntax in a procedural style, and looks like this:

```php
describe('hyperdrive', function () {
  describe('enter_hyperspace()', function () {
    it('does not echo unexpected string', function () {
      $closure = function() { enter_hyperspace('Danger, Will Robinson!'); };
      expect($closure)->not->toEcho('<script>Warning! Warning!</script>');
    });
  });
});
```

Detailed code coverage reports available to the public here: https://codecov.io/gh/comfusion/hyperdrive

And CI builds and build logs available here:
https://travis-ci.org/comfusion/hyperdrive

**Comment by jhabdas** [comment]
@eriktorsner fyi - https://github.com/10up/wp_mock/issues/96

**Comment by jhabdas** [comment]
Good news. I've spoken with collaborators of `WP_Mock` and they [will be applying the GPL](https://github.com/10up/wp_mock/pull/99) to their work so that it may be used with compliance of the terms of the GPL.

**Comment by jhabdas** [comment]
<img width="550" alt="screen shot 2017-06-14 at 11 03 55 am" src="https://user-images.githubusercontent.com/440298/27113731-4d807fe6-50f1-11e7-8e36-db5ffd9b21c5.png">

Looks like Kahlan was a good choice.
