### ISSUE TITLE
Translate README to Spanish

### ISSUE THREAD

**Issue by jhabdas** [comfusion/hyperdrive#53]
mire `/docs/README_ru.md` for ejemplo. @lucasdaniele1 grac por su ajuda

**Comment by jhabdas** [comment]
https://www.w3.org/International/articles/language-tags/

> **The golden rule when creating language tags is to keep the tag as short as possible.** Avoid region, script or other subtags except where they add useful distinguishing information. For instance, use ja for Japanese and not ja-JP, unless there is a particular reason that you need to say that this is Japanese as spoken in Japan, rather than elsewhere.

Code | Language | Subtags
---
en | English | language
mas | Masai | language
fr-CA | French as used in Canada | language+region
es-419 | Spanish as used in Latin America | language+region
zh-Hans | Chinese written with Simplified script | language+script

por favor usar por la idioma de espanol de america del sur `es-419`, por ejemplo `/docs/README_es-419.md`

**Comment by jhabdas** [comment]
https://github.com/comfusion/hyperdrive/new/master?filename=docs/README_es-419.md

Please be sure to copy the _raw_ markdown first from the `README.md` (not the russian example) before translating

**Comment by carlosrgil** [comment]
Pull request https://github.com/comfusion/hyperdrive/pull/54/commits/98b39e3f57aeb3d8ff8e09be745b47e69165034a submitted.
