### ISSUE TITLE
Add Continuous Integration

### ISSUE THREAD

**Issue by jhabdas** [comfusion/hyperdrive#9]
Hyperdrive has been added to the WordPress plugin gallery thanks to @nielslange. To avoid any confusion or excess work, the Subversion repo will need to mirror GH and **no plugin development** should take place within SVN. This repo is to remain our source of truth. And we should make that clear in documentation and the SVN repo. And issues opened in SVN are to be closed immediately and contributors directed to this repo for all plugin development activities.

Relates to #2

- [x] Conventionalize plugin with https://github.com/wp-cli/sample-plugin/
- [x] Add Travis integration with parallel build matrix, linting (for #29) and sample PHPUnit test
- [x] Fix or disable all remaining lint errors for a passing build
- [x] Test building a pull request

**Comment by jhabdas** [comment]
https://github.com/kasparsd/wp-deploy

**Comment by jhabdas** [comment]
https://github.com/gedex/wp-tools

**Comment by eriktorsner** [comment]
I'm pushing from git development to WordPress svn using script for Robo (http://robo.li). Would you consider adding a task runner such as Robo as a project dependency? If so, I'm happy to adapt my script for Integrity Checker to your project.

https://github.com/eriktorsner/integrity-checker/blob/master/RoboFile.php

**Comment by jhabdas** [comment]
Will consider anything that solves the need. We can always improve later. But whatever we do it has to be a dev dependency only, very simple to use. And ideally minimize # total deps while helping ensure repeatability long-term. It should also follow 12 factor app principles. No config in codebase.

**Comment by jhabdas** [comment]
https://12factor.net/

**Comment by jhabdas** [comment]
https://core.trac.wordpress.org/ticket/40663#comment:3

> There exist many Github -> SVN scripts, WordPress does not suggest one over the other - search them up and use whatever fits your development philosophy.

**Comment by jhabdas** [comment]
@nielslange this just became my top priority. could you please grant me access to the SVN repo?

**Comment by jhabdas** [comment]
@EiraStudios any suggestions on approach here?

**Comment by jhabdas** [comment]
Looked at `robo.li`, `wp-tools` and `wp-deploy` and here are my initial thoughts:

**[Robo](http://robo.li/)**

- A task runner
- Uses Composer
- Uses PHP and OO Programming concepts
- Capable of doing just about anything needed

Looks useful, but is more than what we need to accomplish this task. OO programming concepts do not blend well with our functional development philosophy. Introduces Composer when we do not need Composer as we're using NPM, which has a larger and more active developer community.

**[wp-deploy](https://github.com/kasparsd/wp-deploy)**

- Very narrow focus
- Opinionated and requires a specific folder structure
- Built on top of someone else's concept and work
- Has no documentation
- Was last updated 2 years ago

No

**[wp-tools](https://github.com/gedex/wp-tools)**

- Narrow focus, assists in common tasks needed for deploying WP plugins
- Is CLI-based and will integrate well with our NPM scripts
- Integrates concepts from several other tools
- Has good enough documentation and gives links to additional resources
- Is not opinionated on how directories are structured. Uses a dotfile for configuration.

Looks like a good fit for our needs. But we won't know until we try. So this is what we will use.

**Comment by jhabdas** [comment]
@gedex heads up. hyperdrive onboarding

**Comment by jhabdas** [comment]
Blocked on `wp-tools` due to a licensing snafu. Pursuing other options for time to market.

**Comment by jhabdas** [comment]
https://deliciousbrains.com/deploying-wordpress-plugins-travis/

**Comment by jhabdas** [comment]
Done and dusted.
