### ISSUE TITLE
Unexpected token => (AOSP Stock Browser)

### ISSUE THREAD

**Issue by F4bri92** [comfusion/hyperdrive#90]
Noticed `Uncaught SyntaxError: Unexpected token =>` while debugging my website on AOSP stock browser,

Javascript v1.7
err line:` !function(e,t){"object"==typeof exports&&....`

what can I do? :)

**Comment by jhabdas** [comment]
@F4bri92 Thanks for trying the Hyperdrive beta! On the TODO list is to add in backwards compatibility for browsers without [support for `fetch`](http://caniuse.com/#feat=fetch). That will come in a later beta but before the release candidates start.

As a workaround for now to help you test you may use either of the following `fetch`-supporting Android browsers:

<img width="221" alt="screen shot 2017-06-28 at 12 25 09 pm" src="https://user-images.githubusercontent.com/440298/27620547-e95ae774-5bfc-11e7-8e96-0b741f8ffc36.png">

**Comment by F4bri92** [comment]
Ok, you're right! Working as expected with firefox and chrome 👍

**Comment by jhabdas** [comment]
Cool. I'm working on porting a site to WP right now from Jekyll and hitting a lot of friction. When I'm done I'll be back on this plugin and integrating it with that site, which sees 750 organic users per day and will make a good use case to validate the work of Hyperdrive.

Anything else I can do for you right now?

**Comment by F4bri92** [comment]
Just a question... can we manage to detect fetch support and eventually load js without fetch()?

**Comment by jhabdas** [comment]
You betcha. https://github.com/jhabdas/fetch-inject#progressive-enhancement

**Comment by jhabdas** [comment]
Also, not sure if you saw this @F4bri92 but I'm trying to make use as streamlined as possible as I onboard more users as we exit beta. [Info here](https://github.com/comfusion/hyperdrive/issues/70). Feedback welcome.
